#!/usr/bin/env bash
xrandr --output eDP-1 --off --output HDMI-1 --off --output DP-1 --off --output DP-2 --off --output DP-3 --off --output DP-4 --off --output DP-3-1 --mode 1920x1080 --pos 2560x0 --rotate right --output DP-3-2 --primary --mode 2560x1440 --pos 0x197 --rotate normal
