import = ["~/.config/alacritty/kanagawa-dragon.toml"]

[env]
WINIT_X11_SCALE_FACTOR = "1.3"
TERM = "xterm-256color"

[font]
normal = { family = "FiraMono Nerd Font", style = "Regular" }

[cursor]
style = { shape = "Underline", blinking = "On" }
