
[env]
WINIT_X11_SCALE_FACTOR = "1.3"
TERM = "xterm-256color"

[font]
normal = { family = "Monaspace Neon", style = "monospace" }
offset = { x = 0, y = 2 }

[cursor]
style = { shape = "Underline", blinking = "On" }

[general]
import = ["~/.config/alacritty/kanagawa-dragon.toml"]
